
name: Publish to Comfy registry

on:
  workflow_dispatch:  # 手動実行も可能
  push:
    branches:
      - main
      - master
    paths:
      - "pyproject.toml"  # このファイル変更時のみ実行

jobs:
  publish-node:
    name: Publish Custom Node to Comfy Registry
    runs-on: ubuntu-latest

    if: github.event.repository.fork == false  # フォークでは実行しない

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Publish node to Comfy Registry
        uses: Comfy-Org/publish-node-action@main
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
